"""empty message

Revision ID: 478704dd7cc
Revises: None
Create Date: 2015-10-10 23:36:36.133259

"""

# revision identifiers, used by Alembic.
revision = '478704dd7cc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('address', sa.Column('longitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'longitude')
    op.drop_column('address', 'latitude')
    ### end Alembic commands ###
